### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by jungle-boogie** [rparkins999/sqliteman#10]
Hi,

It looks like you've been pretty actively making commits to this project:
https://github.com/rparkins999/sqliteman/commits/master

But there hasn't been a release since April 2019. Do you plan on making a new release anytime soon?

Thanks!

**Comment by rparkins999** [comment]
I do plan on making a new release, but not particularly soon. I want to get a batch of functional improvements completed first. Most of the changes so far since release 1.6.1 are minor fixups or infrastructure updates which don't affect the behaviour but are needed for the functional improvements.
